import { NewsCard } from "@/components/NewsCard"
import { Layout } from "@/components/layout/Layout"
import { INews } from "@/components/types"
import { Grid } from "@mantine/core"
import { GetStaticPaths, GetStaticProps } from "next"
import Head from "next/head"

const categories = [
  "business",
  "entertainment",
  "general",
  "health",
  "science",
  "sports",
  "technology",
]
interface CategoryProps {
  newsData: INews
}
export default function Category({ newsData }: CategoryProps) {
  return (
    <>
      <Head>
        <title>News</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout categories={categories}>
        <Grid columns={5}>
          {newsData.articles.map((article) => (
            <Grid.Col key={article.title}>
              <NewsCard article={article} />
            </Grid.Col>
          ))}
        </Grid>
      </Layout>
    </>
  )
}

export const getStaticPaths: GetStaticPaths = async () => {
  const paths = categories.map((category) => ({
    params: { category },
  }))

  return { paths, fallback: false }
}

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const category = params?.category
  const result = await fetch(
    `https://newsapi.org/v2/top-headlines?country=us&category=${category}&apiKey=${process.env.NEXT_PUBLIC_NEWS_API}`,
  )

  const jsonData = await result.json()
  return {
    props: {
      newsData: jsonData,
    },
  }
}
