import { useSelector } from "react-redux"
import { Layout } from "./../components/layout/Layout"
import { RootState } from "@/redux/store"
import { ArticleList } from "@/components/news_card/ArticleList"
import { EmptyListMessage } from "@/components/EmptyListMessage"
import Head from "next/head"
const categories = [
  "Business",
  "Entertainment",
  "General",
  "Health",
  "Science",
  "Sports",
  "Technology",
]
const Bookmarks = () => {
  const savedArticles = useSelector((state: RootState) => state.articles)
  console.log(savedArticles.length)

  return (
    <>
      <Head>
        <title>Bookmarks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout categories={categories}>
        {savedArticles.length === 0 ? (
          <EmptyListMessage />
        ) : (
          <ArticleList newsData={savedArticles} />
        )}
      </Layout>
    </>
  )
}
export default Bookmarks
