import Head from "next/head"

export default function Home() {
  // const [data, setData] = useState()
  // useEffect(() => {
  //   const fetchData = async () => {
  //     const result = await fetch(
  //       `https://newsapi.org/v2/top-headlines?country=us&category=business&apiKey=${process.env.NEXT_PUBLIC_NEWS_API}`,
  //     )
  //     const jsonData = await result.json()
  //     setData(jsonData)
  //   }
  //   fetchData()
  // }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
